export const GET_RESTAURANTS = "GET_RESTAURANTS";
export const GET_INFO_RESTAURANT = "GET_INFO_RESTAURANT";
export const CLEAR_SEARCH = "CLEAR_SEARCH";
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const SET_LOADING = "SET_LOADING";
export const GET_LOCATION = "  GET_LOCATION";
export const GET_DEFAULT_RESTAURANTS = " GET_DEFAULT_RESTAURANTS";
